- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - freezer-ubuntu-xenial
        - freezer-centos-7:
            voting: false
        - openstack-tox-lower-constraints
        - openstack-tox-pylint
    gate:
      queue: freezer
      jobs:
        - freezer-ubuntu-xenial
        - openstack-tox-lower-constraints
        - openstack-tox-pylint
    experimental:
      jobs:
        - freezer-opensuse-423

- job:
    name: freezer-legacy-dsvm-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer/run.yaml
    post-run: playbooks/legacy/freezer/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-ubuntu-xenial
    parent: freezer-legacy-dsvm-base

- job:
    name: freezer-centos-7
    parent: freezer-legacy-dsvm-base
    nodeset: centos-7

- job:
    name: freezer-opensuse-423
    parent: freezer-legacy-dsvm-base
    nodeset: opensuse-423
