# (c) Copyright 2014,2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provider "libvirt" do |lbv|
    lbv.driver = "kvm"
    lbv.memory = 2048
    lbv.cpus = 2
  end

  config.vm.define "freezer-vm" do |machine|
    machine.vm.box = "trusty64"
    machine.vm.network "private_network" , ip: "10.199.199.199"

    machine.vm.provision :shell, path: "vagrant-scripts/fix-proxy.sh", args: "P-R-O-X-Y", keep_color: true
    machine.vm.provision :shell, path: "vagrant-scripts/deploy-devstack.sh", args: "", keep_color: true
    machine.vm.provision :shell, path: "vagrant-scripts/test-swift.sh", args: "", keep_color: true
  end
end
